refactor: replace use of mustache templates with edx-utils template
openedx/RecommenderXBlock pull request #105
Opened 2024-11-19 10:43 UTC by navinkarkera

Also removes underscore-min.js file which was unused

2024-11-19 10:43 UTC, openedx-webhooks commented
Thanks for the pull request, @navinkarkera!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.


#### :radio_button: Update the status of your PR

Your PR is currently marked as a draft.  After completing the steps above, update its status by clicking "Ready for Review", or removing "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@navinkarkera`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2025-02-04 07:06 UTC, farhan commented
> @farhan Could you please review these changes?

Sure, let me prioritize it.

2025-02-06 07:16 UTC, farhan requested changes
Very good work overall in removing legacy code.

But it will be great if we could directly update the template library to Django Template Library rather than to Mako templates, because we have already parted ways with Mako templates and shifting the code to Django templates library.

ADR:
https://github.com/openedx/open-edx-proposals/blob/ba75a70d7b062426403667822978f101d71fce2d/oeps/best-practices/oep-0067/decisions/frontend/0005-django-templates.rst#L24

2025-02-27 12:04 UTC, itsjeyd commented
@navinkarkera Friendly nudge to follow up on review feedback here.

2025-02-28 05:01 UTC, navinkarkera commented
@itsjeyd Thanks for the reminder.

@farhan Thanks for reviewing this, I'll address your feedback soon (maybe next week).

2025-03-19 14:38 UTC, navinkarkera commented
**Update:** Sorry, could not find time to work on this yet. I'll try to get it done next week.

2025-04-15 14:34 UTC, navinkarkera commented
@farhan We are actually not using mako templates in this repo, the mako like syntax is used by [edx.HtmlUtils.template](https://github.com/openedx/edx-ui-toolkit/blob/3c49a920e9e16ce2ca21e45c3e8f52d54107618d/src/js/utils/html-utils.js#L180-L191) but it has no relation to mako, instead it makes use of [lodash.template](https://lodash.com/docs/4.17.15#template). 

I removed mako from requirements here: https://github.com/openedx/RecommenderXBlock/pull/105/commits/a58ec8bbbf3f0b58c6a5ecd0c5339bbbd2599867

2025-04-18 06:10 UTC, ttqureshi approved these changes
I've reviewed and tested the changes. LGTM ✔️ 

cc: @farhan

2025-04-18 12:31 UTC, farhan approved these changes

2025-04-18 12:49 UTC, merged