RecommenderXBlock: Drop py3.8 support | Replace pkg_resources lib with importlib.resources
openedx/RecommenderXBlock pull request #98
Opened 2024-09-09 09:32 UTC by beingfaisal

2024-09-09 21:12 UTC, mphilbrick211 commented
Hi @beingfaisal! Thanks for this contribution! If you are contributing on behalf of edly, please have your manager reach out to oscm@axim.org to add you to our existing agreement. Thanks!

2024-09-11 07:07 UTC, farhan commented
@beingfaisal All seems ok to me, but will be great to cover following issue within this PR and add support of Python 3.12
https://github.com/openedx/RecommenderXBlock/issues/100

2024-09-11 07:07 UTC, farhan requested changes
Requrest an addition

2024-09-24 13:23 UTC, e0d commented
@beingfaisal are you on the Arbisoft team?

2024-09-24 15:18 UTC, e0d commented
@beingfaisal looks like your branch needs some conflicts resolved, can you have a look?  Otherwise the checks are all passing.

2024-09-27 11:18 UTC, farhan requested changes
1 change

2024-10-02 06:45 UTC, farhan commented on recommender/__init__.py
> +__version__ = '2.2.2'
Please update it to `3.0.0` as we are dropping support of Python 3.8

2024-10-03 07:16 UTC, farhan approved these changes

2024-10-25 16:34 UTC, merged